### ISSUE TITLE
Add text and link in user dashboard explaining where to claim blogs (legacy only)

### ISSUE THREAD

**Issue by lissertations** [hughrun/rockpool#38]
**Who will benefit from your new feature?**
- [x] App users
- [ ] App Maintainers / System Administrators
- [ ] Developers
- [ ] Someone else

**Is your feature request related to a problem? Please describe.**
Upon logging in for the first time, it is likely users may wish to claim an existing (legacy) blog, but there is no clear path on the /user page for them to do this.

**Describe the solution you'd like**
Add a 'claim blog' button under 'Your Blogs', to complement the 'register a blog' option.

**Describe alternatives you've considered**
I could click aimlessly until I found what I'm after, but this seems less efficient.

**What kind of users will this most benefit?**
Users who already have legacy blogs registered and would like to claim them.

**Additional context**
![Screen Shot 2020-03-09 at 21 01 22](https://user-images.githubusercontent.com/22556371/76202865-aba3e100-6249-11ea-836f-b1672ebf7a08.png)

**Comment by lissertations** [comment]
Upon re-reading the /help page such a button could simply link to the 'browse' menu option—it's not immediately obvious to a new user that that's where they need to go in order to claim an existing blog.

**Comment by hughrun** [comment]
This is a good perspective. Ironically the 'claim blog' function was originally in the user page, but it required filling in the URL in a form, which is more error-prone than clicking a button against a prepopulated list.

I agree some clear text with a link would be a good idea.
