### ISSUE TITLE
improvements to user registration page

### ISSUE THREAD

**Issue by lissertations** [hughrun/rockpool#41]
Once a user has registered, they are asked to input their details on the [user](https://github.com/hughrun/rockpool/blob/master/views/user.html) page. The fields for a user's email, twitter and mastodon accounts are too short and don't quite line up. The field text is also bigger than the text on the rest of the page.

It's not clear whether there's any input validation for these fields, nor is there guidance as to what input is expected (e.g. include/omit the leading @ in a twitter or mastodon handle, ensure server is included for mastodon)

![Screen Shot 2020-03-09 at 21 16 39](https://user-images.githubusercontent.com/22556371/76203758-44872c00-624b-11ea-872c-58f1bf8abdfc.png)

**Comment by hughrun** [comment]
There is server-side validation of these fields, primarily because client-side validation has multiple problems including security issues. If you enter text in the wrong format a message will appear explaining how to correct the mistake.

1. Would some placeholder text do the job sufficiently?
2. Should the font size of the labels be increased or that of the fields be decreased?

**Comment by lissertations** [comment]
I tested this but did not receive an error message (Chrome/macOS). 

Additionally, when testing incorrectly-formatted input I noticed that after a couple of changes the 'Update' button appears to stop working (that is, the field remains available to edit) but subsequently clicking the 'Cancel' button saves the changes anyway. 
![Screen Shot 2020-03-09 at 21 49 42](https://user-images.githubusercontent.com/22556371/76206309-ddb84180-624f-11ea-810c-387bec9a4f99.png)

![Screen Shot 2020-03-09 at 21 52 59](https://user-images.githubusercontent.com/22556371/76206537-54553f00-6250-11ea-8eea-229637386104.png)

![Screen Shot 2020-03-09 at 21 49 18](https://user-images.githubusercontent.com/22556371/76206283-d3964300-624f-11ea-9a34-c875b7ab4d63.png)

1. Some placeholder text would be useful, thank you :)
2. The font size of the fields should be decreased, to bring them into line with the rest of the page.

**Comment by lissertations** [comment]
> Additionally, when testing incorrectly-formatted input I noticed that after a couple of changes the 'Update' button appears to stop working (that is, the field remains available to edit) but subsequently clicking the 'Cancel' button saves the changes anyway.

This is probably related to #43.

**Comment by hughrun** [comment]
Soooo I added field validation for all three fields in 31b4479a615bf09ea07d0e92c699f324f44cd336 but then when I moved everything to vuejs components so I could make the page reactive I forgot to keep the field validation... Whoops.
