### ISSUE TITLE
[BUG] App doesn't tell you when it's logged you out on changing user email

### ISSUE THREAD

**Issue by lissertations** [hughrun/rockpool#43]
**Describe the bug**
When a user changes their email address, the app is meant to immediately log them out. However, the app currently does not tell a user that they have been logged out when they change their email address. Additionally, users can continue to make edits to their user details without being aware that they have been logged out. It is unclear whether these edits save properly to the database.

**To Reproduce**
1. Log in, navigate to /user
2. Change email address and/or other details
3. Click 'update'
4. Admire the absence of any error or advice message
5. Continue to update user details

**Expected behavior**
I expected the app to tell me that I had been logged out. It wasn't until I did a forced refresh (cleared cache) that I was returned to the /letmein screen. 

**Desktop (please complete the following information):**
Chrome on macOS

**Comment by hughrun** [comment]
I'll experiment tonight, I think this can be fixed with a "loading" function.

**Comment by hughrun** [comment]
Ooh I see the problem now. It logs out but because it's an AJAX call it doesn't force a redirect to logout. That's a problem!
